DECLARE
user_count NUMBER;

BEGIN
SELECT count(*) INTO user_count FROM dba_users WHERE username = 'TEST';
IF(user_count <= 0)
THEN
EXECUTE IMMEDIATE 'CREATE USER TEST IDENTIFIED BY TEST';
EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO TEST';
END IF;
END;
/
EXIT;

